use_frameworks!

target 'Transform_Example' do
  pod 'Transform', :path => '../'

  target 'Transform_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
